name: burst
channels:
  - conda-forge
  - defaults
dependencies:
  - aiohttp=3.8.1=py310he24745e_0
  - aiosignal=1.2.0=pyhd8ed1ab_0
  - appnope=0.1.2=py310hecd8cb5_1001
  - argon2-cffi=21.3.0=pyhd3eb1b0_0
  - argon2-cffi-bindings=21.2.0=py310hca72f7f_0
  - asttokens=2.0.5=pyhd3eb1b0_0
  - async-timeout=4.0.2=pyhd8ed1ab_0
  - attrs=21.4.0=pyhd8ed1ab_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - blas=1.0=mkl
  - bleach=4.1.0=pyhd3eb1b0_0
  - bottleneck=1.3.2=py310h4e76f89_1
  - brotli=1.0.9=hb1e8313_2
  - brotlipy=0.7.0=py310hca72f7f_1002
  - bzip2=1.0.8=h1de35cc_0
  - ca-certificates=2022.2.1=hecd8cb5_0
  - cachetools=5.0.0=pyhd8ed1ab_0
  - certifi=2020.6.20=pyhd3eb1b0_3
  - cffi=1.15.0=py310hc55c11b_1
  - charset-normalizer=2.0.12=pyhd8ed1ab_0
  - cryptography=36.0.0=py310hf6deb26_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - debugpy=1.5.1=py310he9d5cce_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - entrypoints=0.3=py310hecd8cb5_0
  - executing=0.8.3=pyhd3eb1b0_0
  - fonttools=4.25.0=pyhd3eb1b0_0
  - freetype=2.11.0=hd8bbffd_0
  - frozenlist=1.3.0=py310he24745e_0
  - giflib=5.2.1=haf1e3a3_0
  - google-api-core=2.5.0=pyhd8ed1ab_0
  - google-api-python-client=2.40.0=pyhd8ed1ab_0
  - google-auth=2.6.0=pyh6c4a22f_1
  - google-auth-httplib2=0.1.0=pyhd8ed1ab_0
  - googleapis-common-protos=1.54.0=py310h2ec42d9_0
  - httplib2=0.20.4=pyhd8ed1ab_0
  - idna=3.3=pyhd3eb1b0_0
  - importlib-metadata=4.8.2=py310hecd8cb5_0
  - importlib_metadata=4.8.2=hd3eb1b0_0
  - intel-openmp=2021.4.0=hecd8cb5_3538
  - ipykernel=6.9.1=py310hecd8cb5_0
  - ipython=8.1.1=py310hecd8cb5_0
  - ipython_genutils=0.2.0=pyhd3eb1b0_1
  - jedi=0.18.1=py310hecd8cb5_1
  - jinja2=3.0.3=pyhd3eb1b0_0
  - jpeg=9d=h9ed2024_0
  - jsonschema=3.2.0=pyhd3eb1b0_2
  - jupyter_client=7.1.2=pyhd3eb1b0_0
  - jupyter_core=4.9.2=py310hecd8cb5_0
  - jupyterlab_pygments=0.1.2=py_0
  - kiwisolver=1.3.1=py310he9d5cce_0
  - lcms2=2.12=hf1fd2bf_0
  - libcxx=12.0.0=h2f01273_0
  - libffi=3.3=hb1e8313_2
  - libpng=1.6.37=ha441bb4_0
  - libprotobuf=3.19.1=h8346a28_0
  - libsodium=1.0.18=h1de35cc_0
  - libtiff=4.2.0=h87d7836_0
  - libwebp=1.2.2=h56c3ce4_0
  - libwebp-base=1.2.2=hca72f7f_0
  - lz4-c=1.9.3=h23ab428_1
  - markupsafe=2.0.1=py310hca72f7f_0
  - matplotlib=3.5.1=py310hecd8cb5_0
  - matplotlib-base=3.5.1=py310hfb0c5b7_0
  - matplotlib-inline=0.1.2=pyhd3eb1b0_2
  - mistune=0.8.4=py310hca72f7f_1000
  - mkl=2021.4.0=hecd8cb5_637
  - mkl-service=2.4.0=py310hca72f7f_0
  - mkl_fft=1.3.1=py310hf879493_0
  - mkl_random=1.2.2=py310hc081a56_0
  - multidict=6.0.2=py310he24745e_0
  - munkres=1.1.4=py_0
  - nbclient=0.5.11=pyhd3eb1b0_0
  - nbconvert=6.1.0=py310hecd8cb5_0
  - nbformat=5.1.3=pyhd3eb1b0_0
  - ncurses=6.3=hca72f7f_2
  - nest-asyncio=1.5.1=pyhd3eb1b0_0
  - notebook=6.4.8=py310hecd8cb5_0
  - numexpr=2.8.1=py310hdcd3fac_1
  - numpy=1.21.2=py310h2cbf25c_0
  - numpy-base=1.21.2=py310he490955_0
  - openssl=1.1.1m=hca72f7f_0
  - packaging=21.3=pyhd3eb1b0_0
  - pandas=1.4.1=py310he9d5cce_0
  - pandocfilters=1.5.0=pyhd3eb1b0_0
  - parso=0.8.3=pyhd3eb1b0_0
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pillow=9.0.1=py310hde71d04_0
  - pip=21.2.4=py310hecd8cb5_0
  - prometheus_client=0.13.1=pyhd3eb1b0_0
  - prompt-toolkit=3.0.20=pyhd3eb1b0_0
  - protobuf=3.19.1=py310he9d5cce_0
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - pyasn1=0.4.8=py_0
  - pyasn1-modules=0.2.7=py_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pygments=2.11.2=pyhd3eb1b0_0
  - pyopenssl=22.0.0=pyhd3eb1b0_0
  - pyparsing=3.0.4=pyhd3eb1b0_0
  - pyrsistent=0.18.0=py310hca72f7f_0
  - pysocks=1.7.1=py310hecd8cb5_0
  - python=3.10.0=hdfd78df_5
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python_abi=3.10=2_cp310
  - pytz=2021.3=pyhd3eb1b0_0
  - pyu2f=0.1.5=pyhd8ed1ab_0
  - pyzmq=22.3.0=py310he9d5cce_2
  - readline=8.1.2=hca72f7f_1
  - requests=2.27.1=pyhd8ed1ab_0
  - rsa=4.8=pyhd8ed1ab_0
  - selenium=3.141.0=py310hca72f7f_1000
  - send2trash=1.8.0=pyhd3eb1b0_1
  - setuptools=58.0.4=py310hecd8cb5_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.37.2=h707629a_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - terminado=0.13.1=py310hecd8cb5_0
  - testpath=0.5.0=pyhd3eb1b0_0
  - tk=8.6.11=h7bc2e8c_0
  - tornado=6.1=py310hca72f7f_0
  - traitlets=5.1.1=pyhd3eb1b0_0
  - typing-extensions=4.1.1=hd8ed1ab_0
  - typing_extensions=4.1.1=pyha770c72_0
  - tzdata=2021e=hda174b7_0
  - uritemplate=4.1.1=pyhd8ed1ab_0
  - urllib3=1.26.8=pyhd3eb1b0_0
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - webencodings=0.5.1=py310hecd8cb5_1
  - wheel=0.37.1=pyhd3eb1b0_0
  - xz=5.2.5=h1de35cc_0
  - yarl=1.7.2=py310he24745e_1
  - zeromq=4.3.4=h23ab428_0
  - zipp=3.7.0=pyhd3eb1b0_0
  - zlib=1.2.11=h4dc903c_4
  - zstd=1.4.9=h322a384_0
prefix: /Users/avliu/opt/anaconda3/envs/burst
